### ISSUE TITLE
Generating CSV files

### ISSUE THREAD

**Issue by cookpa** [ftdc-picsl/QuANTs#10]
Hard-coded solution on CFN is going away, need a general method to produce the stats from the antsCT output.

**Comment by jeffduda** [comment]
Some issues that will need to be resolved for this:

1. How generic to go. Currently we assume a directory structure of id/timestamp/ and use that to distinguish time-points. antsCT doesn't require that structure nor does it require the naming convention of id_timestamp_ that we use. We could add an option to assume the id_timestamp_ naming convention and require those to be specified otherwise. 
2. antsCT output does not include a copy of the unprocessed input, which we currently use. Should we drop this from our collected stats.
3. Should we drop any assumptions about directory structures from within functions and just provide examples of how to deal with different possible directory structures.
